create table person (id serial primary key, age int4 not null, name varchar(255) not null);

-- From Hibernate generator 
-- create table person (id int8 generated by default as identity, age int4 not null, name varchar(255) not null, primary key (id));
